ALTER TABLE base_products DROP COLUMN IF EXISTS currency_id;
ALTER TABLE base_products ADD COLUMN currency VARCHAR NOT NULL DEFAULT 'STQ';

ALTER TABLE products DROP COLUMN IF EXISTS currency_id;
ALTER TABLE products ADD COLUMN currency VARCHAR NOT NULL DEFAULT 'STQ';
