interval_s = 5
file_name = "all_offers"
cluster = "stage.stq.cloud"
thread_count = 1

[s3]
region = "us-east-1"
bucket = "storiqa-dev"
key = "AKIAJTQ4IR33MOO6VS2Q"
secret = "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"

[stores_microservice]
url="http://stores:8000"

[warehouses_microservice]
url="http://warehouses:8000"