pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    mount:
    - deps
    restore: true
    when:
      event:
      - pull_request
      - push
      - tag

###
# Test
###

  update_pr:
    image: plugins/git
    commands:
    - export BRANCH_SRC=origin/${DRONE_COMMIT_REFSPEC%%:*} BRANCH_DST=origin/${DRONE_BRANCH}
    - cp -rpf .git .git.bak
    - git config --global user.email "service@storiqa.com" && git config --global user.name "Storiqa Common"
    - git fetch && git checkout $BRANCH_SRC && git merge --no-commit $BRANCH_DST
    - rm -rf .git && mv -f .git.bak .git
    when:
      event: pull_request
  test:
    image: rust:1.26-stretch
    environment:
    - PGPASSWORD=a1a1a1a1
    - RUN_MODE=k8s
    - DATABASE_HOST=db-postgresql
    - DATABASE_URL=postgresql://stores:stores@db-postgresql/stores
    - CARGO_HOME=deps
    commands:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --write-mode=diff
    - apt-get update && apt-get install -y wget gnupg2
    - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
    - apt-get update
    - apt-get install -y libpq5 postgresql-client-10
    - psql -U postgres -h db-postgresql -c "CREATE ROLE stores WITH PASSWORD 'stores' LOGIN REPLICATION" -c "CREATE DATABASE stores OWNER stores"
    - psql -U postgres -h db-postgresql -d stores -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"";
    - wget -q https://s3.eu-central-1.amazonaws.com/dumpster.stq/diesel -O /usr/local/cargo/bin/diesel
    - chmod +x /usr/local/cargo/bin/diesel
    - diesel migration run
    - cargo test
    when:
      event: pull_request

###
# Build and deploy to nightly/stage
###

  build:
    image: rust:1.26-stretch
    environment:
    - CARGO_HOME=deps
    commands:
    - cargo build --release --locked
    when:
      event: push
  package:
    image: plugins/docker
    repo: storiqateam/stq-stores
    tags:
    - ${DRONE_BRANCH//\//_}
    - ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.run
    secrets:
    - docker_username
    - docker_password
    when:
      event: [push, tag]
  deploy2nightly:
    image: jackthestripper/drone_k8s_rollout:20180607
    object: stores
    kind: deployment
    namespace: default
    img_names: storiqateam/stq-stores
    img_cnts: stores
    img_tags: ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - source: k8s_nightly_ca
      target: k8s_ca
    - source: k8s_nightly_user
      target: k8s_user
    - source: k8s_nightly_token
      target: k8s_token
    - source: k8s_nightly_addr
      target: k8s_addr
    when:
      branch: master
      event: push
  deploy2stage:
    image: jackthestripper/drone_k8s_rollout:20180607
    object: stores
    kind: deployment
    namespace: default
    img_names: storiqateam/stq-stores
    img_cnts: stores
    img_tags: ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - source: k8s_stage_ca
      target: k8s_ca
    - source: k8s_stage_user
      target: k8s_user
    - source: k8s_stage_token
      target: k8s_token
    - source: k8s_stage_addr
      target: k8s_addr
    when:
      branch: release*
      event: push

###
# Deploy to stable
###

  deploy2stable:
    image: jackthestripper/drone_k8s_rollout:20180607
    object: stores
    kind: deployment
    namespace: default
    img_names: storiqateam/stq-stores
    img_cnts: stores
    img_tags: ${DRONE_BRANCH//\//_}${DRONE_PARENT_BUILD_NUMBER}
    secrets:
    - source: k8s_stable_ca
      target: k8s_ca
    - source: k8s_stable_user
      target: k8s_user
    - source: k8s_stable_token
      target: k8s_token
    - source: k8s_stable_addr
      target: k8s_addr
    when:
      branch: master
      event: deployment
      environment: stable

###
# Deploy to production
###

  deploy2production:
    image: jackthestripper/drone_k8s_rollout:20180607
    namespace: default
    kind: deployment
    object: stores
    img_names: storiqateam/stq-stores
    img_cnts: stores
    img_tags: ${DRONE_BRANCH//\//_}${DRONE_PARENT_BUILD_NUMBER}
    secrets:
    - source: k8s_prod_ca
      target: k8s_ca
    - source: k8s_prod_user
      target: k8s_user
    - source: k8s_prod_token
      target: k8s_token
    - source: k8s_prod_addr
      target: k8s_addr
    when:
      branch: release*
      event: deployment
      environment: production

###
# Notifications and post-deploy ops
###

  rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    mount:
    - deps
    rebuild: true
    when:
      event:
      - pull_request
      - push
      - tag
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: release
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} succeeded.
      {{else}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} failed.
      {{/success}}
    when:
      event: [ push, tag, deployment ]
      branch: [ master, release* ]
      status: [ failure, success ]

###
# External dependencies for tests
###

services:
  db-postgresql:
    image: postgres:10-alpine
    environment:
    - POSTGRES_PASSWORD=a1a1a1a1
    when:
      event: pull_request
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    when:
      event: pull_request
