FROM rust:1.30-stretch as builder
ARG PROFILE=debug
WORKDIR /build
COPY . .
RUN cargo build --bin ticker

FROM debian:stretch
ARG PROFILE=debug
ENV RUST_LOG=ticker=debug
WORKDIR /app
COPY --from=builder /build/target/${PROFILE}/ticker /app
COPY config /app/config
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y openssl ca-certificates libpq5 \
    && apt-get autoremove -y \
    && apt-get clean -y
ENTRYPOINT ["/app/ticker"]
