version: '3'
services:
  stores:
    image: stores
    build:
      context: .
      dockerfile: Dockerfile.stores
    container_name: stores
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh stores-pg:5432 ; /utils/wait_for_it.sh stores-el:9200 ; diesel migration run ; cargo run"]
    volumes:
      - ..:/app
      - stores_cargo_cache:/usr/local/cargo
    environment:
      - DATABASE_URL=postgresql://stores:stores@stores-pg/stores
    expose:
      - 8000
    stdin_open: true
    depends_on:
      - stores-pg
      - stores-el
    links:
      - stores-el
      - stores-pg

  stores-pg:
    image: postgres:10
    container_name: stores-pg
    volumes:
      - stq-stores-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stores
      - POSTGRES_DB=stores
      - POSTGRES_PASSWORD=stores
    

  stores-el:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: stores-el
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - stq-stores-elastic-data:/var/lib/elasticsearch/data
    


volumes:
  stores_cargo_cache:
  stq-stores-postgres-data:
  stq-stores-elastic-data:

networks:
  default:
    external:
      name: storiqa
