ALTER TABLE base_products ADD COLUMN length_cm INTEGER NOT NULL DEFAULT (0);
ALTER TABLE base_products ADD COLUMN width_cm INTEGER NOT NULL DEFAULT (0);
ALTER TABLE base_products ADD COLUMN height_cm INTEGER NOT NULL DEFAULT (0);
ALTER TABLE base_products ADD COLUMN weight_g INTEGER NOT NULL DEFAULT (0);
