-- This file should undo anything in `up.sql`
ALTER TABLE stores DROP COLUMN IF EXISTS address;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS address VARCHAR NOT NULL DEFAULT 'def_address';
ALTER TABLE stores DROP COLUMN IF EXISTS email;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS email VARCHAR NOT NULL DEFAULT 'def_email';
ALTER TABLE stores DROP COLUMN IF EXISTS phone;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS phone VARCHAR NOT NULL DEFAULT 'def_phone';
ALTER TABLE stores DROP COLUMN IF EXISTS currency_id;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS currency_id INTEGER NOT NULL REFERENCES currencies (id);
ALTER TABLE stores DROP COLUMN IF EXISTS language_id;
ALTER TABLE stores DROP COLUMN IF EXISTS slogan;