
ALTER TABLE stores 
    ALTER COLUMN address DROP NOT NULL,
    ALTER COLUMN email DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS default_language INTEGER NOT NULL REFERENCES languages (id) DEFAULT 1;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS slogan VARCHAR;
