[server]
host = "0.0.0.0"
port = "8001"
database = "postgresql://stores:stores@stores-pg/stores"
elastic = "stores-es:9200"
thread_count = 20

[client]
http_client_buffer_size=3
http_client_retries=3
dns_worker_thread_count=4
