# TODO: remove.
[S3]
region = "us-east-1"
bucket = "storiqa-dev"
key = "AKIAJTQ4IR33MOO6VS2Q"
secret = "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"

[graylog]
addr = "udplog.stq.cloud:32303"

[rocket_retail]
interval_s = 3600
file_name = "all_offers"
cluster = "stage.stq.cloud"
thread_count=1
