[server]
address = "0.0.0.0:8000"
database = "postgresql://stores:stores@stores-pg-postgresql/stores"
thread_count = 20

[client]
http_client_buffer_size=3
http_client_retries=3
dns_worker_thread_count=4
