version: '3'
services:
  rocket-retail:
    image: rocket-retail
    build:
      context: .
      dockerfile: Dockerfile.rocket-retail
    container_name: rocket-retail
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh stores:8000; cargo run --locked"]
    volumes:
      - ../../vendor:/vendor
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - "RUST_LOG=rocket-retail=debug"
    ports:
      - "8000"
    expose:
      - 8000
    stdin_open: true
#    depends_on:
#      - stores
#      - warehouses
#    links:
#      - stores
#      - warehouses

volumes:
  stq_cargo_cache:

networks:
  default:
    external:
      name: storiqa
